modLoader = "javafml"
loaderVersion = "[${fancymodloader_version},)"
license = "MIT"

[[mods]]
modId = "logicchips"
version = "${version}"
displayName = "Logic Chips"
authors = "IchPhilipp & ZZZank"
description = '''
Logic Gates for fancy redstone logic
'''
issueTrackerURL="https://github.com/philoufilou/Logic-Chips/issues"
displayURL="https://github.com/philoufilou/Logic-Chips"
logoFile="icon.png"

[[dependencies.logicchips]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge_version_base},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.logicchips]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.logicchips]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"